### ISSUE TITLE
the command line hangs when using an apostrophe.

### ISSUE THREAD

**Issue by triantares** [Elive/elive-assistant#2]
When using a single apostrophe (') the shell will hang waiting for a second one to close the quote/hyphenation.
This happens when using possessive phrases like "it's" or "the dog's bone" requiring a "backslash" to escape the apostrophe, or not using it at all.

**Comment by Thanatermesis** [comment]
For me it seems to work, it is your issue in a wrong use of the console instead? the correct way should be to enclose the input between " chars, like on the example, if you don't do that, your shell will do what you had (so basically the problem is not on the tool), example:

```
~ ❯❯❯ elive-assistant synonyms "that is a test"
that is a test
~ ❯❯❯ elive-assistant synonyms "that's a test"
that's a test
~ ❯❯❯ elive-assistant synonyms that's a test
> 
^C
~ ❯❯❯ 1
```

**Comment by triantares** [comment]
> and even without the echo, I close this issue because is not a bug, is the normal behaviour of the cli

I know it is but if wanting to promote this elive feature...... shouldn't we cater for 'ease of use' i.e Ux when using 'elive-ai'?

Or , in the Ux case: Solely concentrate on the GUI version?

**Comment by Thanatermesis** [comment]
> Or , in the Ux case: Solely concentrate on the GUI version?

not necesarily, but the commandline needs to be used in the way the commandline is used, so the message should be between " chars "

> elive-assistant something "my question bla bla"

**Comment by triantares** [comment]
> the commandline needs to be used in the way the commandline is used

You are definitely NOT going to get Ux kudos for that comment. :rofl:
